stages:
  - test
  - build
  - deploy

.install-dependencies:
  before_script:
    - apt update -y
    - apt install curl -y
    - apt install git -y
    - git --version
    - yarn install

.install-node-yarn-dependencies:
  before_script:
    - apt update -y
    - apt install git -y
    - apt install -y sudo curl
    - curl --version
    - curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    - sudo apt install -y nodejs
    - node -v
    - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt update && sudo apt install -y yarn
    - yarn install

default:
  image: node:18.18-alpine

build-dev:
  stage: build
  before_script:
    - export CI_BENCHMARK=remote_data
    - export PALINDROME_TYPE=basic
  script:
    - yarn install --ignore-scripts
    - |
      yarn parcel dev/index.html --no-cache &
      until curl -s http://localhost:1234 > /dev/null; do
        echo "Waiting for Parcel server..."
        sleep 1
      done
    - cd services/tsdbService
    - yarn install
    - yarn build
  artifacts:
    paths:
      - "dist/"
  allow_failure: false
  when: manual

build-storybook:
  stage: build
  before_script:
    - apk update
    - apk add bash
    - apk add git
  script:
    - yarn install
    - 'file_path="stories/oth.stories.js"'
    - 'start_pattern="export const localLiveMonitoring"'
    - 'end_pattern="fetchFunction: localMonitoring.*};"'
    - 'sed -i "/$start_pattern/,/$end_pattern/d" "$file_path"' 
    - yarn build-storybook
  artifacts:
    paths:
      - "storybook-static/"
  allow_failure: false
  when: manual

cypress-test:
  stage: test
  extends: .install-dependencies
  dependencies: []
  image: cypress/base:latest
  script:
    - yarn storybook &
    - yarn dev &
    - rm -rf cypress/match-screenshots/ .cache/
    - for i in 1 2; do yarn cypress:run; done
  allow_failure: false

.launch-benchmark-remote-data:
  stage: test
  image: ghcr.io/puppeteer/puppeteer:latest 
  script:
    - |
      for file in data-examples/*; do
        if [ -f "$file" ]; then
          if grep -q "localhost" "$file"; then
            echo "Processing $file"
            sed -i "s/localhost/${INFLUX_PROMETHEUS_SERVER}/g" "$file"
            sed -i "s/'token'/'${INFLUX_TOKEN}'/g" "$file"
          fi
        fi
      done
    - yarn install --ignore-scripts
    - |
      yarn parcel dev/index.html --no-cache &
      until curl -s http://localhost:1234 > /dev/null; do
        echo "Waiting for Parcel server..."
        sleep 1
      done
    - cd services/tsdbService
    - yarn install
    - |
      yarn dev &
      until curl -s http://localhost:9009 > /dev/null; do
        echo "Waiting for palindrome service..."
        sleep 1
      done
    - cd ../..
    - node "$BENCHMARK_SCRIPT"
  allow_failure: false

initial_remote-data-benchmark:
  extends: .launch-benchmark-remote-data
  before_script:
    - export CI_BENCHMARK=remote_data
    - export PALINDROME_TYPE=basic
    - export BENCHMARK_SCRIPT=./scripts/remoteDataBenchmark/remoteDataBenchmark.js

remote-data-update-multiviewport-benchmark:
  extends: .launch-benchmark-remote-data
  before_script:
    - export CI_BENCHMARK=multi-viewports
    - export PALINDROME_TYPE=basic
    - export BENCHMARK_SCRIPT=./scripts/remoteDataBenchmark/multiViewportBenchmark.js

benchmark:
  image: ubuntu:20.04
  stage: test
  dependencies: []
  extends: .install-node-yarn-dependencies
  script:
    - /bin/bash ./scripts/benchmark.sh "classic"
  allow_failure: false

benchmark-test:
  image: ubuntu:20.04
  stage: test
  dependencies: []
  extends: .install-node-yarn-dependencies
  script:
    - /bin/bash ./scripts/benchmark.sh "evaluation"
  allow_failure: false

pages:
  stage: deploy
  image: busybox
  dependencies:
    - build-dev
  script:
    - mv dist/ public/
  artifacts:
    paths:
      - "public/"
  allow_failure: false

gh-pages:
  stage: deploy
  dependencies:
    - build-dev
    - build-storybook
  before_script:
    - apk update
    - apk add bash
    - apk add git
  script:
    - git remote set-url origin "https://${GITLAB_USER_NAME}:${GITLAB_GHPAGES_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - yarn install
    - mv storybook-static/ dist/storybook/
    - yarn dev-deploy
  artifacts:
    paths:
      - "dist/"
  allow_failure: false
  when: manual

mirror-wiki:
  stage: deploy
  image:
    entrypoint: ['']
    name: alpine/git:latest

  before_script:
    - git clone "https://${GITLAB_USER_NAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.wiki.git" "${CI_COMMIT_SHA}"
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"

  script:
    - cd "${CI_COMMIT_SHA}"
    - rm -rf .git
    - git init
    - git config --global user.name "${GH_USERNAME}"
    - git remote add origin "https://${GH_USERNAME}:${GH_TOKEN}@github.com/Smile-SA/palindrome.js.wiki.git"
    - git add .
    - git commit -m "wiki update"
    - git push -f origin master
  allow_failure: false
  when: manual
