  push-to-deploy:
    stage: deploy
    image:
      entrypoint: ['']
      name: alpine/git:latest

    before_script:
      # Clone the repository via HTTPS inside a new directory
      - git clone -b deploy "https://${GITLAB_USER_NAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git" "${CI_COMMIT_SHA}"

      # Set the displayed user with the commits that are about to be made
      - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
      - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"
      
    script:
      # Go to the new directory
      - cd "${CI_COMMIT_SHA}"

      # Add all generated files to Git
      - git add -- . :!.gitlab-ci.yml
      
      - git push origin deploy:deploy-test


    allow_failure: false
    when : manual