stages:
  - test
  - build
  - deploy

.install-dependencies:
  before_script:
    - apt update -y
    - apt install curl -y
    - apt install git -y
    - git --version
    - yarn install

.install-node-yarn-dependencies:
  before_script:
    - apt update -y
    - apt install git -y
    - apt install -y sudo curl
    - curl --version
    - curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    - sudo apt install -y nodejs
    - node -v
    - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key
    - curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add
    - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - sudo apt update && sudo apt install -y yarn
    - yarn install

default:
  image: node:18.18-alpine

build-dev:
  stage: build
  before_script:
    - apk update
    - apk add bash
    - apk add git
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - "dist/"
  allow_failure: false
  when: manual

cypress-test:
  stage: test
  extends: .install-dependencies
  dependencies: []
  image: cypress/base:latest
  script:
    - yarn storybook &
    - yarn dev &
    - rm -rf cypress/match-screenshots/ .cache/
    - for i in 1 2; do yarn cypress:run; done
  allow_failure: false

benchmark:
  image: ubuntu:20.04
  stage: test
  dependencies: []
  extends: .install-node-yarn-dependencies
  script:
    - /bin/bash benchmark.sh "classic"
  allow_failure: false

benchmark-test:
  image: ubuntu:20.04
  stage: test
  dependencies: []
  extends: .install-node-yarn-dependencies
  script:
    - /bin/bash benchmark.sh "evaluation"
  allow_failure: false

pages:
  stage: deploy
  image: busybox
  dependencies:
    - build-dev
  script:
    - mv dist/ public/
  artifacts:
    paths:
      - "public/"
  allow_failure: false

mirror-wiki:
  stage: deploy
  image:
    entrypoint: ['']
    name: alpine/git:latest

  before_script:
    - git clone "https://${GITLAB_USER_NAME}:${GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.wiki.git" "${CI_COMMIT_SHA}"
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"

  script:
    - cd "${CI_COMMIT_SHA}"
    - rm -rf .git
    - git init
    - git config --global user.name "${GH_USERNAME}"
    - git remote add origin "https://${GH_USERNAME}:${GH_TOKEN}@github.com/Smile-SA/palindrome.js.wiki.git"
    - git add .
    - git commit -m "wiki update"
    - git push -f origin master
  allow_failure: false
  when: manual
