version: '3.9'
services:
  palindrome:
    build: .
    container_name: palindrome_c
    environment:
      NODE_ENV: production
    ports:
      - 1234:1234
    volumes:
      - .:/app/palindromeJS
      - ./app/palindromeJS/node_modules
