version: '3.9'
services:
  palindrome:
    build: .
    container_name: palindrome_c
    environment:
      NODE_ENV: production
    ports:
      - 1234:1234
  local_live_monitoring:
    build: ./services/localMonitoringServer
    privileged: true
    container_name: local_live_monitoring_c
    environment:
      NODE_ENV: production
    ports:
      - "9000:9000"
